# Generated by Django 5.1 on 2024-09-01 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='otp_code',
            field=models.CharField(default='none', max_length=10),
        ),
    ]
