# Generated by Django 4.1 on 2024-09-05 22:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_appuser_otp_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_one', models.FileField(blank=True, default='none', upload_to='account_files/profile_photos/')),
                ('image_two', models.FileField(blank=True, default='none', upload_to='account_files/profile_photos/')),
                ('image_three', models.FileField(blank=True, default='none', upload_to='account_files/profile_photos/')),
                ('image_four', models.FileField(blank=True, default='none', upload_to='account_files/profile_photos/')),
                ('image_five', models.FileField(blank=True, default='none', upload_to='account_files/profile_photos/')),
                ('image_six', models.FileField(blank=True, default='none', upload_to='account_files/profile_photos/')),
                ('image_seven', models.FileField(blank=True, default='none', upload_to='account_files/profile_photos/')),
                ('image_eight', models.FileField(blank=True, default='none', upload_to='account_files/profile_photos/')),
                ('image_nine', models.FileField(blank=True, default='none', upload_to='account_files/profile_photos/')),
                ('image_ten', models.FileField(blank=True, default='none', upload_to='account_files/profile_photos/')),
                ('image_eleven', models.FileField(blank=True, default='none', upload_to='account_files/profile_photos/')),
                ('image_twelve', models.FileField(blank=True, default='none', upload_to='account_files/profile_photos/')),
                ('image_thirteen', models.FileField(blank=True, default='none', upload_to='account_files/profile_photos/')),
                ('image_fourtheen', models.FileField(blank=True, default='none', upload_to='account_files/profile_photos/')),
                ('image_fivetheen', models.FileField(blank=True, default='none', upload_to='account_files/profile_photos/')),
                ('image_sixteen', models.FileField(blank=True, default='none', upload_to='account_files/profile_photos/')),
                ('image_seventeen', models.FileField(blank=True, default='none', upload_to='account_files/profile_photos/')),
                ('image_eighteen', models.FileField(blank=True, default='none', upload_to='account_files/profile_photos/')),
                ('image_nineteen', models.FileField(blank=True, default='none', upload_to='account_files/profile_photos/')),
                ('image_twenty', models.FileField(blank=True, default='none', upload_to='account_files/profile_photos/')),
                ('image_twenty_one', models.FileField(blank=True, default='none', upload_to='account_files/profile_photos/')),
                ('title', models.CharField(default='none', max_length=50)),
                ('price', models.CharField(default='none', max_length=30)),
                ('price_per_sqft', models.CharField(default='none', max_length=30)),
                ('category', models.CharField(default='none', max_length=30)),
                ('description', models.TextField(default='none')),
                ('bedroom_number', models.CharField(default='none', max_length=20)),
                ('bathroom_number', models.CharField(default='none', max_length=20)),
                ('garage', models.CharField(default='none', max_length=20)),
                ('address', models.CharField(default='none', max_length=120)),
                ('city', models.CharField(default='none', max_length=20, null=True)),
                ('state', models.CharField(default='none', max_length=20, null=True)),
                ('postal_code', models.CharField(default='none', max_length=20, null=True)),
                ('country', models.CharField(default='none', max_length=20, null=True)),
                ('area', models.CharField(default='none', max_length=20, null=True)),
                ('property_attachment_one', models.FileField(default='none', null=True, upload_to='account_files/profile_photos/')),
                ('property_attachment_two', models.FileField(default='none', null=True, upload_to='account_files/profile_photos/')),
                ('property_attachment_three', models.FileField(default='none', null=True, upload_to='account_files/profile_photos/')),
                ('property_attachment_four', models.FileField(default='none', null=True, upload_to='account_files/profile_photos/')),
                ('property_id', models.CharField(default='none', max_length=20)),
                ('property_size', models.CharField(default='none', max_length=20)),
                ('garage_size', models.CharField(default='none', max_length=20)),
                ('year_built', models.CharField(default='none', max_length=20)),
                ('property_type', models.CharField(default='none', max_length=20)),
                ('property_status', models.CharField(default='none', max_length=20)),
                ('first_floor', models.FileField(blank=True, default='none', upload_to='account_files/profile_photos/')),
                ('second_floor', models.FileField(blank=True, default='none', upload_to='account_files/profile_photos/')),
                ('third_floor', models.FileField(blank=True, default='none', upload_to='account_files/profile_photos/')),
                ('fourth_floor', models.FileField(blank=True, default='none', upload_to='account_files/profile_photos/')),
                ('status', models.BooleanField(default=False)),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('app_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.appuser')),
            ],
        ),
    ]
