# Generated by Django 5.1 on 2024-09-07 15:47

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_property'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleTour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tour_type', models.CharField(default='In Person', max_length=100)),
                ('tour_date', models.DateField()),
                ('tour_time', models.TimeField()),
                ('message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('prop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.property')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.appuser')),
            ],
        ),
    ]
