# Generated by Django 5.1 on 2024-09-08 08:17

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_propertybookmark'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReserveProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookmarked_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('prop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.property')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.appuser')),
            ],
        ),
    ]
